os: osx
osx_image: xcode10.1
language: swift

install:
- brew update
- brew install mint

script:
- xcodebuild test -project ./MovieAround.xcodeproj -scheme MovieAround -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
